name = "cloudflare-pexels-randomizer"
main = "src/index.js"
compatibility_date = "2025-01-21"

# Cloudflare Dashboard'dan bu değişkenleri tanımlayacağız.
# Local testler için .dev.vars dosyası kullanılır ama repoya atılmaz.
[vars]
# Bu değer public olabilir, sorun yok. Ancak API Key gizli kalmalı.
# https://www.pexels.com/collections/albania-3j1q9fg/
DEFAULT_COLLECTION_ID = "3j1q9fg"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
invocation_logs = true
