name = "cloudflare-pexels-randomizer"
main = "src/index.js"
compatibility_date = "2025-01-21"

# Cloudflare Dashboard'dan bu değişkenleri tanımlayacağız.
# Local testler için .dev.vars dosyası kullanılır ama repoya atılmaz.
[vars]
# Bu değer public olabilir, sorun yok. Ancak API Key gizli kalmalı.
# Varsayılan bir koleksiyon ID'si bırakabiliriz veya boş bırakabiliriz.
DEFAULT_COLLECTION_ID = "983745"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
invocation_logs = true
